name: revthefox.co.uk
title: "index"
email: rev@revthefox.co.uk
description: >
  My personal site. No guarantee of coherence.
baseurl: ""
url: "https://revthefox.co.uk"
blog_url: "https:/blog.revthefox.co.uk"
twitter_username: TheReverend403
github_username:  TheReverend403
keybase_username: thereverend403

keep_files: [.well-known, tg, files]
markdown: kramdown
sass:
    style: compressed

compress_html:
    clippings: all
    comments: all
    endings: all
    profile: false
    ignore:
        envs: [dev]
